Add NfSpy: NFS UID/GID spoofer
ThePorgs/Exegol-images pull request #131
Opened 2023-04-07 07:47 UTC by Couskito

# Description

Add NfsPy : UID/GID spoofer tool to exploit NFSv3 shares : https://github.com/bonsaiviking/NfSpy

2023-04-11 10:54 UTC, ShutdownRepo requested changes

2023-04-11 10:54 UTC, ShutdownRepo commented on sources/install.sh
> +  apt install -y libfuse-dev
this should be changed to `fapt libfuse-dev`

2023-04-11 10:54 UTC, ShutdownRepo commented on sources/install.sh
> +}
Can you add `add-history` if you have some command example in mind?

2023-04-11 10:55 UTC, ShutdownRepo commented
Thank you for this PR. Changing target branch to `dev.

2023-04-15 18:41 UTC, QU35T-code commented on sources/install.sh
> +  python2 -m pip install fuse-python
In order to work in an isolated environment, can you add a python venv like this ?

```bash
virtualenv -p /usr/bin/python2 ./venv
./venv/bin/python2 -m pip install fuse-python
./venv/bin/python2 setup.py install
chmod +x scripts/*
sed -i "s#/usr/bin/env python#/opt/tools/NfSpy/venv/bin/python2#" /opt/tools/NfSpy/scripts/nfspy
sed -i "s#/usr/bin/env python#/opt/tools/NfSpy/venv/bin/python2#" /opt/tools/NfSpy/scripts/nfspysh
ln -v -s /opt/tools/NfSpy/scripts/nfspy /opt/tools/bin/nfspy
ln -v -s /opt/tools/NfSpy/scripts/nfspysh /opt/tools/bin/nfspysh
```

2023-04-28 12:34 UTC, closed without merging