Add project-discovery katana tool.
ThePorgs/Exegol-images pull request #150
Opened 2023-04-27 11:52 UTC by Fisjkars

Adapt changes from https://github.com/ThePorgs/Exegol-images/pull/128/files

2023-04-27 11:57 UTC, QU35T-code requested changes

2023-04-27 11:57 UTC, QU35T-code commented on sources/install/package_web.sh
> +    install_katana                  # Crawling and Spidering by projectdiscovery.io
In order to keep a coherent architecture, can you move this line 1 row above so that the functions are in the order in which they are called ?

2023-04-27 11:57 UTC, QU35T-code commented on sources/install/package_web.sh
> +  # Crawling and Spidering
This comment isn't necessary.

2023-04-27 12:18 UTC, Fisjkars commented
Done

2023-04-27 12:20 UTC, QU35T-code commented
Thanks !

2023-04-28 20:56 UTC, ShutdownRepo commented
Can you sync with `dev`? It seems you don't have the latest changes made on the workflows, which makes the pipeline fail on the ARM64 runner

2023-05-03 15:14 UTC, closed without merging