Add password Spraying tool (SMB, OWA, Lync, Cisco ASA etc...)
ThePorgs/Exegol-images pull request #151
Opened 2023-04-27 11:53 UTC by Fisjkars

Adapt changes from https://github.com/ThePorgs/Exegol-images/pull/130/files

2023-04-27 12:01 UTC, QU35T-code requested changes
Hey @Fisjkars,

Thanks ! I request some changes.

2023-04-27 12:01 UTC, QU35T-code commented on sources/install/package_ad.sh
> +  # Password Spraying tool for Active Directory Credentials.
This comment is not necessary.

2023-04-27 12:01 UTC, QU35T-code commented on sources/install/package_ad.sh
> +  git -C /opt/tools/ clone https://github.com/Greenwolf/Spray.git
Can you add `--depth=1` after the `clone` so that it doesn't download everything ?

2023-04-27 12:18 UTC, Fisjkars commented
Done

2023-04-27 12:21 UTC, QU35T-code approved these changes

2023-04-27 17:30 UTC, ShutdownRepo approved these changes

2023-04-28 20:56 UTC, ShutdownRepo commented
Can you sync with `dev`? It seems you don't have the latest changes made on the workflows, which makes the pipeline fail on the ARM64 runner

2023-05-03 15:14 UTC, closed without merging