Dev Add Cloud tools (cloudsplaining, cloudsploit and prowler)
ThePorgs/Exegol-images pull request #180
Opened 2023-06-29 17:06 UTC by clomic

# Description
Add Cloud security assessment tools (cloudsplaining, cloudsploit and prowler)

2023-07-01 15:38 UTC, clomic commented on sources/install/package_cloud.sh
> +    git -C /opt/tools/ clone https://github.com/aquasecurity/cloudsploit
Done (thks)

2023-07-06 15:31 UTC, QU35T-code commented
@clomic,

Can you merge with the remote dev branch ? Otherwise, the update of the donpapi tool will block the workflow

2023-07-17 09:48 UTC, clomic commented on sources/install/package_cloud.sh
> +    add-aliases cloudsploit
done

2023-07-17 09:57 UTC, QU35T-code requested changes

2023-07-17 09:57 UTC, QU35T-code commented on sources/assets/zsh/aliases.d/cloudsploit
> +alias cloudsploit='/opt/cloudsploit/index.js'
> `/opt/tools/cloudsploit` (missing `tools`)

Not fixed.

2023-07-17 09:57 UTC, QU35T-code commented on sources/install/package_cloud.sh
> +    cd /opt/cloudsploit && npm install
> `/opt/tools/cloudsploit` (missing `tools`)

Not fixed.

2023-07-18 14:10 UTC, clomic commented
Sorry, the directory was wrong (/opt/cloudsploit instead of /opt/tools/cloudsploit)...

2023-07-18 14:15 UTC, QU35T-code commented
@clomic,

Can you check all my requests ? 
The directory is also wrong here : sources/assets/zsh/aliases.d/cloudsploit

2023-07-18 14:51 UTC, clomic commented
Done

2023-07-18 19:27 UTC, QU35T-code approved these changes

2023-07-19 18:25 UTC, ShutdownRepo approved these changes

2023-07-19 18:25 UTC, merged