[Fix] - CMSMAP exploitdb path
ThePorgs/Exegol-images pull request #280
Opened 2023-11-21 23:22 UTC by jenaye

# Description

> when I was using the tool I noticed that the path specified in the configuration file was incorrect, which prevents it from being used.

This is just a small contribution and not the cleanest but at least it works

![image](https://github.com/ThePorgs/Exegol-images/assets/15458329/42a5b6a8-d851-4f6c-9ad9-129b7722abfe)

2023-11-22 10:33 UTC, ShutdownRepo requested changes
Nice!
In order to make this fix cleaner, let's switch from a pipx install to git clone + venv in order to edit the .conf before the pipx install
What do you think?

2023-11-23 09:48 UTC, QU35T-code requested changes

2023-11-23 09:48 UTC, QU35T-code commented on sources/install/package_web.sh
> +    sed -i 's|/usr/share/exploitdb/|/opt/tools/exploitdb/|g' /root/.local/pipx/venvs/cmsmap/lib/python3.9/site-packages/cmsmap/cmsmap.conf
Please, replace `python3.9` with a wildcard to avoid version issues -> `sed -i 's|/usr/share/exploitdb/|/opt/tools/exploitdb/|g' /root/.local/pipx/venvs/cmsmap/lib/python*/site-packages/cmsmap/cmsmap.conf`

2023-11-23 09:48 UTC, QU35T-code commented
Can you fix conflicts ? (merge with dev branch)

2023-11-23 14:41 UTC, ShutdownRepo commented on sources/install/package_web.sh
> +    sed -i 's|/usr/share/exploitdb/|/opt/tools/exploitdb/|g' /root/.local/pipx/venvs/cmsmap/lib/python3.9/site-packages/cmsmap/cmsmap.conf
Won't be needed if the changes I suggested above get implemented (edit the `cmsmap.conf` file before building the python virtual env)

2024-01-26 16:54 UTC, ShutdownRepo commented
@jenaye, closing this Pull Request for inactivity
If you ever see this message, please update your PR so that the conflicts are resolved 😉

2024-01-26 16:54 UTC, closed without merging