Adding WiFi dockerfile
ThePorgs/Exegol-images pull request #290
Opened 2024-01-19 18:25 UTC by stevesec

# Description

> A description of your PR, what it brings or corrects. Don't forget to configure your PR to the dev branch (cf. https://exegol.readthedocs.io/en/latest/community/contributors.html)

# Related issues

> If your PR responds to an issue for a bug fix or feature request, make sure to includes references to the issues (e.g. "fixes #xxxx").

# Point of attention

> Things you are not sure about that deserve special attention if you have doubts or questions.

2024-01-24 10:10 UTC, ShutdownRepo requested changes
Thank you for the pull request!
The dockerfile seems good to me, but I have some change requests, see the comments below

2024-01-24 10:10 UTC, ShutdownRepo commented on sources/install/package_ad.sh
This is a nice addition, but in my opinion it should be added in a separate pull request.
Also, regarding the review of that particular addition:
- you forgot to call the function at the bottom of the file in the package function
- why not install the tool via `go install -v $URL`?
- you used `add-history` and `add-aliases` but the corresponding files do not exist
- in `add-to-list`, the description of the tool should be changed to something like "an mitm tool for helping with relay attacks" as it doesn't only do DHCPv6

2024-01-24 10:10 UTC, ShutdownRepo commented on .github/workflows/entrypoint_preprod_wifi.yml
This file will not be needed as the wifi image will not be built along official images for now as indicated in #288
The dockerfile will allow users to build their local image easily

2024-01-25 16:31 UTC, stevesec commented on .github/workflows/entrypoint_preprod_wifi.yml
Understood. Thank you!

2024-01-25 16:32 UTC, stevesec commented on sources/install/package_ad.sh
Ah understood! I will make the necessary changes!

2024-01-25 16:55 UTC, stevesec commented on sources/install/package_ad.sh
Updated in 141c33243193935f922b1e7a2861391ec5884b15

2024-01-25 20:28 UTC, ShutdownRepo requested changes

2024-01-25 20:28 UTC, ShutdownRepo commented on sources/install/package_ad.sh
The addition of pretender should be made in a specific, separate, Pull Request

2024-01-26 16:52 UTC, ShutdownRepo requested changes

2024-01-26 16:52 UTC, ShutdownRepo commented on sources/install/package_ad.sh
Indeed, #294 is created, but the changes still show here, please remove the pretender changes from here and only keep `wifi.dockerfile`

2024-01-26 20:26 UTC, closed without merging