Create pretender
ThePorgs/Exegol-images pull request #295
Opened 2024-01-26 20:10 UTC by stevesec

# Description

> A description of your PR, what it brings or corrects. Don't forget to configure your PR to the dev branch (cf. https://exegol.readthedocs.io/en/latest/community/contributors.html)

# Related issues

> If your PR responds to an issue for a bug fix or feature request, make sure to includes references to the issues (e.g. "fixes #xxxx").

# Point of attention

> Things you are not sure about that deserve special attention if you have doubts or questions.

2024-01-26 21:56 UTC, ShutdownRepo requested changes

2024-01-26 21:56 UTC, ShutdownRepo commented on sources/install/package_ad.sh
don't forget to add the call to the install function 😉

2024-01-26 22:08 UTC, stevesec commented on sources/install/package_ad.sh
*slaps head*

2024-01-27 00:06 UTC, ShutdownRepo approved these changes

2024-01-27 00:07 UTC, ShutdownRepo commented
Careful, the target branch was wrong, fixed it

2024-01-30 08:53 UTC, QU35T-code approved these changes

2024-01-30 10:01 UTC, ShutdownRepo commented
@stevesec can you make push a change on the PR so that I can run the appropriate pipeline? Any change will do, synchronizing on the dev branch would be relevant for example

2024-02-09 10:08 UTC, QU35T-code requested changes

2024-02-09 10:08 UTC, QU35T-code commented on sources/assets/shells/history.d/pretender
> +# Pretender History.d
Please remove this comment (I know Shutdown asked you ;))

2024-02-10 14:44 UTC, ShutdownRepo approved these changes

2024-02-10 14:44 UTC, merged

2024-02-10 14:44 UTC, ShutdownRepo commented
Thank you @stevesec ! 💪

2024-02-12 20:12 UTC, stevesec commented
And thank you both for this amazing repo!