Reducing the size of venv by using common packages
ThePorgs/Exegol-images pull request #310
Opened 2024-02-22 10:22 UTC by QU35T-code

# Description

The **package_base** installs the most frequently used python packages (**top 25**).
Then the python venv uses the **system environment** to avoid duplicating packages and save installation time.

# Related issues

The images are too big !

2024-02-22 10:27 UTC, ShutdownRepo requested changes
nice! let's do it as well for pipx-installed tools

2024-02-22 10:27 UTC, ShutdownRepo commented on sources/assets/python/requirements.txt
let's add impacket

2024-02-22 10:27 UTC, ShutdownRepo commented on sources/install/package_base.sh
> +    pip install -r /root/sources/assets/python/requirements.txt
let's explicitly say `pip3`, no ?

2024-02-22 11:21 UTC, ShutdownRepo approved these changes

2024-02-26 09:48 UTC, ShutdownRepo commented
@QU35T-code can you remind here how much space and build time was gained? (for future reference when preparing the `dev -> main` release)

2024-02-26 09:59 UTC, QU35T-code commented
Sure :

```bash
Build time : 1h30 vs 1h45
Size : 52Go vs 55go
```

2024-04-02 17:36 UTC, ShutdownRepo approved these changes

2024-04-02 17:36 UTC, merged