Firefox policy
ThePorgs/Exegol-images pull request #325
Opened 2024-04-08 23:55 UTC by lap1nou

# Description

This aim to simplify the maintenance of the Firefox configuration using Firefox policy (https://mozilla.github.io/policy-templates/). Firefox policy can be very powerful to unify the Exegol Firefox configuration into one single file which contributors can easily contribute to.

For example, adding a single bookmark can be a tedious task since a contributor would need to download and open the SQLite database and this also means the bookmarks aren't visible easily.

If everything works fine, all we should need to do is place this `policies.json` file in the Firefox folder, I tested this on an Exegol container and it worked like a charm, this is also what I'm using in my NixOS config and it seems to work fine.

# Related issues

N / A

# Point of attention

Of course this is a simple example, if you like the idea, I can expand the policy file in order to add already presents bookmarks and extension.

2024-04-10 10:42 UTC, ShutdownRepo commented
Awesome! @Dramelac and I think this could also be interesting in my-resources as well
I would gladly merge an expanded version of this 🙏

2024-04-10 17:54 UTC, lap1nou commented
Hey @ShutdownRepo I updated the policy, it should:

- Install all the already present extension (UA Switcher, Cookie Editor, Dark Reader, FoxyProxy, Wappalyzer)
- Install the Burpsuite certficate
- Add all already present bookmarks and some additional, feel free to tell me if you want to get rid of some or want to add more while we are at it

If you think the policy is fine like that, I can remove the current Firefox install Python script and modify the current install script to copy the policy in the correct folder.

Regards.

2024-04-10 18:12 UTC, ShutdownRepo commented
awesome, @Skileau as you developed the initial firefox integrations, do you mind checking this out and share your pov?
whatever the outcome, I'm putting this PR on hold as we are in the process of image release, we will merge afterwards, in order to have this change tested in nightly before release

2024-04-10 20:49 UTC, Skileau commented
Very interesting!
This would probably be much more optimized than my basic and functional implementation.

I would be glad to take a look at this next week end.

2024-04-30 09:28 UTC, QU35T-code commented
@lap1nou,

Can you specify into which folder we need to add this file ? I tried and didn't reproduce

2024-04-30 09:53 UTC, lap1nou commented
Hello @QU35T-code,

In `/usr/lib/firefox-esr/distribution/policies.json`.

Regards.

2024-04-30 09:53 UTC, Skileau commented
@lap1nou Could you please also explain from where/how you extracted the addons names to enter them in the configuration file?

2024-04-30 09:55 UTC, lap1nou commented
Hey @Skileau,

I added a comment in the JSON file for this specific reason:
```json
"ExtensionSettings_Comment": "To get the 'ID' of a plugins, type 'about:memory' in Firefox url bar, source: https://stackoverflow.com/questions/48056506/get-add-on-id-of-extensions-in-firefox"
```

This is the only way I found unfortunately.

Regards.

2024-04-30 10:33 UTC, Skileau commented
Thank you for the information @lap1nou 🙂 
We have already implemented an automated way to retrieve this ID, I just wanted to make sure that you did not have a more optimised way to do so.

As discussed with @ShutdownRepo on Discord, we will keep our script to retrieve the ID of addons and use it to generate a policy.json file automatically with the structure you suggest (hardcoded values require a manual operation and may cause malfunctions in future updates).

2024-04-30 17:03 UTC, lap1nou commented
Good @Skileau,

Do you want me to do all of this in this PR ?

2024-05-06 12:09 UTC, Skileau commented
Hi @lap1nou as you prefer 🙂
I can work on the integration of policy.json in the existing code if you want.

Otherwise here are the next steps:
- update addons installation feature + bookmarks management by replacing "manual" installation with the generation of a Firefox policy.
- integrate this feature to [Exegol-images](https://github.com/ThePorgs/Exegol-images) as well to install default addons at image build.

2024-05-07 10:03 UTC, gbe commented on sources/assets/firefox/policies.json.template
> +            "name": "OCD AD Minmap"
Mindmap I guess

2024-06-03 16:14 UTC, lap1nou commented
For me, I think it should be ready @QU35T-code

2024-06-04 16:37 UTC, Skileau commented
Hello :)
All good for me except the "trust-ca-burp.sh" integration to the web installer package.
The first objective of this script was to generate a BurpCommunity CA specific to each Exegol instance and trust it, it was not expected to be run at the image build.

If we run it at build, wouldn't it trust the same CA for everyone and lead to a potential MitM risk for users of Firefox in Exegol?

2024-06-04 18:00 UTC, lap1nou commented
Good catch @Skileau sorry for that mistake, about the `my-resources` part, do you know  what file I should modify so that end users can place their own Firefox policy file in `my-resources` ?

2024-07-11 10:47 UTC, lap1nou commented
Greetings,

I think this is finished, I'll let you test aswell.

@Skileau I've tried to modifiy the idea a bit for the `my-resources` customisations, the user should be able to provide a whole Firefox policy instead of the default one provided so he can manage his own Bookmarks / Addons and also other settings.

If a user place a file `policies.json` in `my-resources/setup/firefox/`, it should be used normally, here is an example that we can put in `my-resources`:
```json
{
  "policies": {
    "Policy_Comment": "All Firefox policy directive can be found here: https://mozilla.github.io/policy-templates/",
    "DisableTelemetry": true,
    "DisplayBookmarksToolbar": "always",

    "ManagedBookmarks": [
      {
        "toplevel_name": "Exegol Bookmarks - This the name of the folder where bookmarks are going to be stored"
      },
      {
        "url": "https://exegol.readthedocs.io/en/latest/",
        "name": "Exegol Doc - This is a single URL bookmark"
      },
      {
        "name": "References / Guides - This is a subfolder containing an array of bookmark",
        "children": [
          {
            "url": "https://www.thehacker.recipes/",
            "name": "THR"
          }
        ]
      },
      {
        "name": "Tools - This is another subfolder containing an array of bookmark",
        "children": [
          {
            "url": "file:///opt/tools/CyberChef/CyberChef.html",
            "name": "CyberChef"
          },
          {
            "url": "https://regex101.com/",
            "name": "Regex101"
          },
          {
            "url": "https://macvendors.com/",
            "name": "MA:CV:en:do:rs"
          }
        ]
      }
    ],

    "ExtensionSettings_Comment": "To get the 'ID' of a plugins, go to the plugin page and search for this string in the page source code: \"guid\":\", for the extension DarkReader, the guid is: addon@darkreader.org",
    "ExtensionSettings": {
      "addon@darkreader.org": {
        "installation_mode": "force_installed",
        "install_url": "https://addons.mozilla.org/firefox/downloads/latest/darkreader/latest.xpi"
      }
    },
    
    "UserMessaging": {
      "WhatsNew": false,
      "ExtensionRecommendations": false,
      "FeatureRecommendations": false,
      "UrlbarInterventions": false,
      "SkipOnboarding": true,
      "MoreFromMozilla": false
    },

    "Certificates": {
      "Install": ["/opt/tools/firefox/cacert.der"]
    }
  }
}
```

I also had to modify the script to trust the CA otherwise I would get this error: 
```
Error: LinkageError occurred while loading main class burp.StartBurp
        java.lang.UnsupportedClassVersionError: burp/StartBurp has been compiled by a more recent version of the Java Runtime (class file version 65.0)
```

Regards.

2024-10-01 16:50 UTC, ShutdownRepo commented
@Skileau what do you think here?

2024-10-02 08:07 UTC, Skileau commented
I have reviewed the code, everything seems to be ok.
I am currently building the image to test "dynamically". I will let you know once I have tested all the features :)

2024-10-02 10:47 UTC, Skileau commented
Hi again, all good for me, you can merge @ShutdownRepo :slightly_smiling_face:

2024-10-02 13:58 UTC, ShutdownRepo commented
Thank you @Skileau, @lap1nou can you create the right PR on the documentation repo? Once the doc PR is alright, we'll merge both at the same time

2024-11-17 14:04 UTC, ShutdownRepo commented
There are conflicts to solve here, and the documentation needs to be done as well. 
Putting this PR on hold in the mean time

2024-11-17 14:05 UTC, ShutdownRepo requested changes
Documentation to be done, and conflicts to solve

2025-02-22 12:54 UTC, ShutdownRepo commented
@lap1nou @Skileau I would like to merge this PR before the next release, happening in a few days
In my opinion we're good to go here and on https://github.com/ThePorgs/Exegol-docs/pull/72
Can you confirm, in case there's something to fix/add/remove first?

2025-02-25 13:57 UTC, lap1nou commented
Hey @ShutdownRepo, I will build an image to test this, I'm currently struggling to build it (error related to asdf missing), but this should be ok by the end of the day for me.

2025-02-25 22:41 UTC, lap1nou commented
Here is what tests I did:

- Built the image -> OK (had to modify a few things but not related to this PR)
- Started Firefox -> Addons and bookmarks are here -> OK
- Ran `trust-ca-burp` -> tried to intercept HTTPS traffic with Burp -> OK
- I also manually added a new bookmark and extension (outside those defined in the policy)

This seems fine for me.

@Skileau for the image to build I quickly added those things:
```shell
export PATH="/opt/tools/bin:$PATH"
export PATH="$HOME/.asdf/shims:$PATH"
```
in the `install_asdf` function.

and also replaced the `set_asdf_env` by this function:
```shell
function set_asdf_env() {
    colorecho "Setting env for asdf"
    #source "$HOME/.asdf/asdf.sh"
    export PATH="/opt/tools/bin:$PATH"
    export PATH="$HOME/.asdf/shims:$PATH"
}
```

of course this is just a temp fix just to build the image to test while waiting for someone to fix asdf stuff properly.

2025-02-25 23:39 UTC, ShutdownRepo commented
Thank you both, you probably didn't have an up-to-date nightly because those changes were fixed very very recently (74b542adfef2b98b04b3d92f3892933ca7ad609d).
@lap1nou I'll trust your tests! Will run the pipeline here as soon as we manage to build a nightly image (we're having a few troubles here and there).
In the mean time, @Skileau if you manage to run some tests of your own or if you're having doubts on anything, feel free to raise your concerns 😄

If we're patient enough, we could merge this PR in a few weeks and I'll buy everyone a one year birthday cake for this pull request 🎂🎉

2025-02-25 23:39 UTC, ShutdownRepo approved these changes

2025-02-27 00:05 UTC, merged