Fix binwalk dependencies
ThePorgs/Exegol-images pull request #348
Opened 2024-05-13 20:19 UTC by lap1nou

# Description

Greetings,

When running something along the line of: `binwalk -e test.sqhfs --run-as=root`, I get:
```
WARNING: Extractor.execute failed to run external extractor 'unsquashfs -d 'squashfs-root' '%e'': [Errno 2] No such file or directory: 'unsquashfs', 'unsquashfs -d 'squashfs-root' '%e'' might not be installed correctly
```

The `unsquashfs` dependency is not installed, this PR aim to fix that, it also move the binwalk install in it's own install function.

# Related issues

N/A

# Point of attention

Binwalk list other dependency such as `sasquatch` (https://github.com/ReFirmLabs/binwalk/blob/master/INSTALL.md), since I haven't encountered a case where those were needed I propose to add them later on if necessary.

2024-05-14 11:21 UTC, ShutdownRepo requested changes
Do you mind importing the changes from https://github.com/ThePorgs/Exegol-images/pull/347 in this PR? So that we avoid conflicts

2024-06-03 13:53 UTC, QU35T-code requested changes

2024-06-03 13:53 UTC, QU35T-code commented on sources/install/package_forensic.sh
> +
Can you remove this empty line ?

2024-06-03 13:54 UTC, QU35T-code commented on sources/install/package_forensic.sh
> +
@lap1nou

2024-06-04 08:48 UTC, QU35T-code approved these changes

2024-06-04 08:48 UTC, QU35T-code commented
Thx @lap1nou !

2024-06-08 00:43 UTC, merged