Adding smuggler.py
ThePorgs/Exegol-images pull request #87
Opened 2023-01-26 12:34 UTC by fransosiche

Hello,

As @wlayzz suggested, I added the tool smuggler.py to Exegol (very cool project btw).

2023-01-26 13:08 UTC, ShutdownRepo commented
Nice addition! I'll let you fix the conflict and we'll merge that 👍

2023-01-26 13:40 UTC, fransosiche commented
Thx, conflict fixed, should be good !

2023-01-26 13:52 UTC, QU35T-code requested changes
Hello @fransosiche,

Thank you for your participation to the Exegol project !
To be really precise, I propose some small fixes and that will be perfect I think !

2023-01-26 13:52 UTC, QU35T-code commented on sources/install.sh
> +
Here, there is one empty line.

2023-01-26 13:52 UTC, QU35T-code commented on sources/zsh/aliases.d/smuggler
> +alias smuggler.py='python3 /opt/tools/smuggler/smuggler.py'
There is no newline at the end of the file.

2023-01-26 13:52 UTC, QU35T-code commented on sources/zsh/history.d/smuggler
> +smuggler -u "http://$TARGET/"
There is no newline at the end of the file.

2023-01-26 13:52 UTC, QU35T-code commented on sources/install.sh
> +
There is an extra line between the 2 functions.

2023-01-26 13:58 UTC, fransosiche commented
Good point @QU35T-code 

I fixed it !

2023-01-27 09:54 UTC, ShutdownRepo approved these changes

2023-01-27 09:55 UTC, ShutdownRepo commented
Thank you for the review @QU35T-code, and @fransosiche for this PR!
Ready to merge, putting it in waitlist because of the current works on the CI/CD pipeline

2023-01-27 10:38 UTC, QU35T-code approved these changes

2023-02-23 09:48 UTC, Dramelac commented
Hello @fransosiche

Sorry to repeat the process again but it's the last time!
Can you update your PR with the dev branch to resolve conflicts (this update will also merge the new CI/CD pipeline)

After that we will be able to run the test and merge your PR!

And thank you for your contribution!

2023-02-23 09:58 UTC, fransosiche commented
Hello @Dramelac, 

it should be good !

2023-02-23 20:59 UTC, merged